#rm(list=ls()) 
#setwd("~/Documents/GitHub/BNPconsistency/scripts_for_figures")
## read sources
require(e1071)
require(mclust)
require(MASS)
require(bayesm)

require(MCMCpack)
require(mvtnorm)
require(Runuran)
require(flexclust)
library(gridExtra)
library(cowplot)
library(ggplot2)
library(latex2exp)
require(tidyr)
library(dplyr)
library(JuliaCall)
library(viridis)
source("~/Documents/GitHub/BNPconsistency/scripts_for_figures/Utils_post.R")
source("~/Documents/GitHub/BNPconsistency/scripts_for_figures/plt_Figure15.R")

df_fig15 = plt_fig15( input_file = "~/Documents/GitHub/BNPconsistency/saves_for_figures/cmp_fig15.RData", 
                      c_vec =seq(0.01, 2, length.out = 30),fig_path= "~/Documents/GitHub/BNPconsistency/figures/Figure15/" )