#rm(list=ls()) 
#setwd("~/Documents/GitHub/BNPconsistency/scripts_for_figures")
## read sources
require(e1071)
require(mclust)
require(MASS)
require(bayesm)
require(MCMCpack)
require(mvtnorm)
require(Runuran)
require(flexclust)
library(gridExtra)
library(cowplot)
library(ggplot2)
library(latex2exp)
require(tidyr)
library(dplyr)
library(JuliaCall)
library(viridis)
source("~/Documents/GitHub/BNPconsistency/scripts_for_figures/Utils_post.R")
source("~/Documents/GitHub/BNPconsistency/scripts_for_figures/plt_Figure2.R")

# Ek =5
#alpha_list<- c(1.24, 0.81, 0.6,0.56)

plt_fig2(input_file = "~/Documents/GitHub/BNPconsistency/saves_for_figures/cmp_fig9.RData", c_v =c(0.1, 0.5, 1, 2),alpha_list= c(1.24, 0.81, 0.6,0.56),n_list = c(200,2000,20000,40000), fig_path= "~/Documents/GitHub/BNPconsistency/figures/Figure2/" )
