# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatrix.proto\x12\x08\x62\x61yesmix\"(\n\x06Vector\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x01\x42\x02\x10\x01\"H\n\x06Matrix\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x10\n\x08rowmajor\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR.fields_by_name['data']._options = None
  _VECTOR.fields_by_name['data']._serialized_options = b'\020\001'
  _MATRIX.fields_by_name['data']._options = None
  _MATRIX.fields_by_name['data']._serialized_options = b'\020\001'
  _VECTOR._serialized_start=26
  _VECTOR._serialized_end=66
  _MATRIX._serialized_start=68
  _MATRIX._serialized_end=140
# @@protoc_insertion_point(module_scope)
