# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: semihdp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ls_state_pb2 as ls__state__pb2
import matrix_pb2 as matrix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsemihdp.proto\x12\x08\x62\x61yesmix\x1a\x0els_state.proto\x1a\x0cmatrix.proto\"\xf2\x04\n\x0cSemiHdpState\x12;\n\x0brestaurants\x18\x01 \x03(\x0b\x32&.bayesmix.SemiHdpState.RestaurantState\x12\x31\n\x06groups\x18\x02 \x03(\x0b\x32!.bayesmix.SemiHdpState.GroupState\x12\x31\n\x04taus\x18\x03 \x03(\x0b\x32#.bayesmix.SemiHdpState.ClusterState\x12\t\n\x01\x63\x18\x04 \x03(\x05\x12\t\n\x01w\x18\x05 \x01(\x01\x1a\xf1\x01\n\x0c\x43lusterState\x12,\n\x0cuni_ls_state\x18\x01 \x01(\x0b\x32\x14.bayesmix.UniLSStateH\x00\x12\x30\n\x0emulti_ls_state\x18\x02 \x01(\x0b\x32\x16.bayesmix.MultiLSStateH\x00\x12:\n\x14lin_reg_uni_ls_state\x18\x04 \x01(\x0b\x32\x1a.bayesmix.LinRegUniLSStateH\x00\x12)\n\rgeneral_state\x18\x05 \x01(\x0b\x32\x10.bayesmix.VectorH\x00\x12\x13\n\x0b\x63\x61rdinality\x18\x03 \x01(\x05\x42\x05\n\x03val\x1a\x8e\x01\n\x0fRestaurantState\x12\x38\n\x0btheta_stars\x18\x01 \x03(\x0b\x32#.bayesmix.SemiHdpState.ClusterState\x12\x11\n\tn_by_clus\x18\x02 \x03(\x05\x12\x17\n\x0ftable_to_shared\x18\x03 \x03(\x05\x12\x15\n\rtable_to_idio\x18\x04 \x03(\x05\x1a$\n\nGroupState\x12\x16\n\x0e\x63luster_allocs\x18\x01 \x03(\x05\"\x80\x03\n\rSemiHdpParams\x12?\n\x0cpseudo_prior\x18\x01 \x01(\x0b\x32).bayesmix.SemiHdpParams.PseudoPriorParams\x12\x1f\n\x17\x64irichlet_concentration\x18\x02 \x01(\x01\x12\x1a\n\x12rest_allocs_update\x18\x03 \x01(\t\x12\x16\n\x0etotalmass_rest\x18\x04 \x01(\x01\x12\x15\n\rtotalmass_hdp\x18\x05 \x01(\x01\x12\x35\n\x07w_prior\x18\x06 \x01(\x0b\x32$.bayesmix.SemiHdpParams.WPriorParams\x1a[\n\x11PseudoPriorParams\x12\x13\n\x0b\x63\x61rd_weight\x18\x01 \x01(\x01\x12\x17\n\x0fmean_perturb_sd\x18\x02 \x01(\x01\x12\x18\n\x10var_perturb_frac\x18\x03 \x01(\x01\x1a.\n\x0cWPriorParams\x12\x0e\n\x06shape1\x18\x01 \x01(\x01\x12\x0e\n\x06shape2\x18\x02 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semihdp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEMIHDPSTATE._serialized_start=58
  _SEMIHDPSTATE._serialized_end=684
  _SEMIHDPSTATE_CLUSTERSTATE._serialized_start=260
  _SEMIHDPSTATE_CLUSTERSTATE._serialized_end=501
  _SEMIHDPSTATE_RESTAURANTSTATE._serialized_start=504
  _SEMIHDPSTATE_RESTAURANTSTATE._serialized_end=646
  _SEMIHDPSTATE_GROUPSTATE._serialized_start=648
  _SEMIHDPSTATE_GROUPSTATE._serialized_end=684
  _SEMIHDPPARAMS._serialized_start=687
  _SEMIHDPPARAMS._serialized_end=1071
  _SEMIHDPPARAMS_PSEUDOPRIORPARAMS._serialized_start=932
  _SEMIHDPPARAMS_PSEUDOPRIORPARAMS._serialized_end=1023
  _SEMIHDPPARAMS_WPRIORPARAMS._serialized_start=1025
  _SEMIHDPPARAMS_WPRIORPARAMS._serialized_end=1071
# @@protoc_insertion_point(module_scope)
